[package]
edition.workspace = true
name = "koe-core"
version.workspace = true

[features]
aec = []
cli = []
default = ["aec", "cli", "screen-audio", "system-audio"]
gui = []
screen-audio = []
system-audio = []

[dependencies]
fs2 = { workspace = true }
getrandom = { workspace = true }
koe-ffi = { workspace = true }
log = { workspace = true }
ogg = { workspace = true }
serde_json = { workspace = true }
shiguredo_opus = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "fs",
  "io-util",
  "macros",
  "rt-multi-thread",
  "sync",
  "time",
] }
workspace-hack.workspace = true

[lints]
workspace = true
