[package]
edition.workspace = true
name = "koe-cli"
version.workspace = true

[[bin]]
name = "koe"
path = "src/main.rs"

[dependencies]
usage.workspace = true
koe-core = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
symphonia = { workspace = true, features = [
  "aac",
  "aiff",
  "flac",
  "isomp4",
  "mp3",
  "ogg",
  "pcm",
  "vorbis",
  "wav",
] }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "rt-multi-thread",
  "signal",
  "sync",
  "time",
] }
toml = { workspace = true }

[lints]
workspace = true
