[package]
edition.workspace = true
name = "oto-encode"
version.workspace = true

[dependencies]
getrandom = { workspace = true }
ogg = { workspace = true }
rubato = { workspace = true }
shiguredo_opus = { workspace = true }
thiserror = { workspace = true }
workspace-hack = { workspace = true }

[lints]
workspace = true
